services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      API_INTERNAL_URL: http://backend:8000
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    healthcheck:
      disable: true
